cryticArgs: ["--solc-remaps",     "ds-test/=lib/forge-std/lib/ds-test/src/
        erc1363-payable-token/=lib/erc1363-payable-token/
        erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/
        forge-std/=lib/forge-std/src/
        openzeppelin-contracts/=lib/openzeppelin-contracts/
        openzeppelin/=lib/openzeppelin-contracts/contracts/
        solmate/=lib/solmate/src/
        @openzeppelin/=lib/openzeppelin-contracts/
        foundry-huff/=lib/foundry-huff/src/
        huffmate/=lib/huffmate/src/
        solidity-stringutils/=lib/foundry-huff/lib/solidity-stringutils/
        stringutils/=lib/foundry-huff/lib/solidity-stringutils/"]